### ISSUE TITLE
semver minimum version requirement

### ISSUE THREAD

**Issue by vdorie** [dlt-hub/dlt#2115]
### dlt version

1.4.0

### Describe the problem

`semver` is listed as requiring `>=2.13.0`, however `semver.Version` (referenced in a few places, including [here](https://github.com/dlt-hub/dlt/blob/b4d807fc059591720f1ea14e73340e9a98041225/dlt/common/warnings.py#L9)) was only introduced with version [3.0.0](https://github.com/python-semver/python-semver/blob/master/CHANGELOG.rst#features-1). This causes `dlt` to fail at import on systems with `semver` already installed at 2.13.0, giving:

```
AttributeError: module 'semver' has no attribute 'Version'
```

### Expected behavior

dlt should be able to be used on systems that meet its stated requirements.

### Steps to reproduce

```sh
python3 -m venv test_env
source test_env/bin/activate
pip install semver==2.13.0 dlt
```

```python
import dlt
```

### Operating system

Linux, macOS

### Runtime environment

Local

### Python version

3.11

### Additional information

It looks as if `semver.Version` was introduced with 47633c6, so the issue also impacts 1.3.0.
