### PR TITLE
(fix) 3351 fixes default type var

### LINKED ISSUE #3351: import dlt not working in databricks job compute version 15.4LTS
### dlt version

1.18.2

### Describe the problem

Followed steps here --> https://dlthub.com/docs/dlt-ecosystem/destinations/databricks#enable-dlt-on-a-cluster on databricks cluster version 15.4 LTS but didnt work. **_This setup did work on 16.4LTS version_**

### Setup
```
%%capture
%pip install dlt[databricks]
%restart_python

import dlt
from dlt.sources.rest_api import (
    RESTAPIConfig,
    rest_api_resources,
)
```

### Error
```
TypeError: Too few arguments for <class 'dlt.extract.items_transform.ItemTransform'>; actual 1, expected 2
File <command-5155516115746829>, line 1
----> 1 import dlt
      2 from dlt.sources.rest_api import (
      3     RESTAPIConfig,
      4     rest_api_resources,
      5 )


File /usr/lib/python3.11/typing.py:293, in _check_generic(cls, parameters, elen)
    291 alen = len(parameters)
    292 if alen != elen:
--> 293     raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
    294                     f" actual {alen}, expected {elen}")
```

### Expected behavior

_No response_

### Steps to reproduce

- Initialize a databricks job compute version 15.4 LTS by configuring init script mentioned here --> https://dlthub.com/docs/dlt-ecosystem/destinations/databricks#enable-dlt-on-a-cluster
- Then spin up a notebook and paste the below code 
```
%%capture
%pip install dlt[databricks]
%restart_python

import dlt
from dlt.sources.rest_api import (
    RESTAPIConfig,
    rest_api_resources,
)
```

### Operating system

macOS

### Runtime environment

Local

### Python version

3.13

### dlt data source

REST api

### dlt destination

_No response_

### Other deployment details

Destination --> Databricks

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rudolfix**
### Description
fixes #3351

### CODE REVIEW

**Review by anuunchin — APPROVED** [review]
🧠
