### ISSUE TITLE
Remove reference to abandoned package `ratelimiter` in Handling API Rate Limits

### ISSUE THREAD

**Issue by ecerulm** [dlt-hub/dlt#3644]
### Documentation description

The page https://dlthub.com/docs/general-usage/http/requests#handling-api-rate-limits mentions [`ratelimiter`](https://github.com/RazerM/ratelimiter) that project was archived on 2023-10-03 and no longer works on python 3.13 `AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'? `   

I think it is best to remove the reference to `ratelimiter` or provide a link to the right pypi package. 

### Are you a dlt user?

I'm considering using dlt, but the documentation is unclear.

**Comment by anuunchin** [comment]
Hi @ecerulm, did you end up using another library? (maybe pyrate-limiter) 

Would be great if you open a PR to replace the ratelimiter reference with an alternative that's actively maintained

**Comment by ecerulm** [comment]
> Hi [@ecerulm](https://github.com/ecerulm), did you end up using another library? (maybe pyrate-limiter)

At the end I ended up implementing my own rate limiter. 

> Would be great if you open a PR to replace the ratelimiter reference with an alternative that's actively maintained

Sure I can create a PR to update the docs

**Comment by anuunchin** [comment]
Fyi, I included the adjustment in a larger doc PR.
