### ISSUE TITLE
'SqlalchemyCredentials' object has no attribute '_conn_lock'

### ISSUE THREAD

**Issue by AugustMathisen** [dlt-hub/dlt#2990]
### dlt version

1.15.0

### Describe the problem

I want to load some data from a local file into the project's SQL server database. One of the requirements is that we can connect via Entra ID, and we have made that work using a SQL Alchemy destination, similar to the description in this [thread](https://github.com/dlt-hub/dlt/issues/2193#issuecomment-2592389164). However, this only seems to work for dlt version 1.6-1.9. When I upgrade to 1.10 and above, I get the error message `AttributeError: 'SqlalchemyCredentials' object has no attribute '_conn_lock'`.

### Expected behavior

Pipeline runs without error

### Steps to reproduce

Python script that causes error:
[dltErrorDemo.txt](https://github.com/user-attachments/files/21749613/dltErrorDemo.txt)

Note: There is some extra complexity here related to using Entra ID for connecting to the DB. This is a requirement from the project's side, and is the primary reason why we need to use a SQLAlchemy destination rather than an mssql destination.

### Operating system

Windows

### Runtime environment

Local

### Python version

3.11

### dlt data source

CSV

### Other deployment details

SQLAlchemy destination
