### ISSUE TITLE
import dlt not working in databricks job compute version 15.4LTS

### ISSUE THREAD

**Issue by siddhardhapalepu** [dlt-hub/dlt#3351]
### dlt version

1.18.2

### Describe the problem

Followed steps here --> https://dlthub.com/docs/dlt-ecosystem/destinations/databricks#enable-dlt-on-a-cluster on databricks cluster version 15.4 LTS but didnt work. **_This setup did work on 16.4LTS version_**

### Setup
```
%%capture
%pip install dlt[databricks]
%restart_python

import dlt
from dlt.sources.rest_api import (
    RESTAPIConfig,
    rest_api_resources,
)
```

### Error
```
TypeError: Too few arguments for <class 'dlt.extract.items_transform.ItemTransform'>; actual 1, expected 2
File <command-5155516115746829>, line 1
----> 1 import dlt
      2 from dlt.sources.rest_api import (
      3     RESTAPIConfig,
      4     rest_api_resources,
      5 )


File /usr/lib/python3.11/typing.py:293, in _check_generic(cls, parameters, elen)
    291 alen = len(parameters)
    292 if alen != elen:
--> 293     raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
    294                     f" actual {alen}, expected {elen}")
```

### Steps to reproduce

- Initialize a databricks job compute version 15.4 LTS by configuring init script mentioned here --> https://dlthub.com/docs/dlt-ecosystem/destinations/databricks#enable-dlt-on-a-cluster
- Then spin up a notebook and paste the below code 
```
%%capture
%pip install dlt[databricks]
%restart_python

import dlt
from dlt.sources.rest_api import (
    RESTAPIConfig,
    rest_api_resources,
)
```

### Operating system

macOS

### Runtime environment

Local

### Python version

3.13

### dlt data source

REST api

### Other deployment details

Destination --> Databricks

**Comment by anuunchin** [comment]
Leaving a relevant note here: It may be fixed with removing default from
```
   TCustomMetrics = TypeVar(
       "TCustomMetrics", covariant=True, bound=Mapping[str, Any], default=Dict[str, Any]
   )
```

and explicitly provide type parameters to implementations:

```
FilterItem(ItemTransform[bool]) → FilterItem(ItemTransform[bool, Dict[str, Any]])
```

**Comment by rudolfix** [comment]
@siddhardhapalepu the reason is very old version of typing-extensions when you have in the env. those scripts are running on Python 3.11.

we'll update our dependencies, and you should be able run those. in the meantime you can try to update typing-extensions before importing dlt, 4.12.0 will do
