### ISSUE TITLE
Bug: adjust dlt to pipdeptree or remove it

### ISSUE THREAD

**Issue by AstrakhantsevaAA** [dlt-hub/dlt#539]
dlt deploy doesn’t work with pipdeptree==2.12.0
downgraded to 2.9.3, now it works
```module 'pipdeptree' has no attribute 'get_installed_distributions'```
