### ISSUE TITLE
Databricks init script - monkey patching dlt internal error

### ISSUE THREAD

**Issue by AndreiBondarenko** [dlt-hub/dlt#3201]
### dlt version

1.17.1

### Describe the problem

When attempting to run dlt on a job cluster on Databricks, using runtime 16.4 LTS , I encountered the following error:

```
Unexpected internal error when monkey patching dlt module: cannot import name 'overrides' from partially initialized module 'dlt' (most likely due to a circular import) (/databricks/python/lib/python3.12/site-packages/dlt/__init__.py)
```

### Expected behavior

dlt runs on as it did on previous Databricks runtimes

### Steps to reproduce

Use the init script from the current documentation on a Databricks job cluster with runtime version 16.4 LTS.

### Operating system

Linux, Other

### Runtime environment

Other

### Python version

3.12

### Additional information

I had already altered one of the paths in the init script to get it to work on 15.4 LTS in the past. This was based on a discussion I found in some reddit post. So I'm assuming the paths have changed again.

**Comment by Nimpruda** [comment]
Honestly the most consistent way of running dlthub on databricks without having this issue that I've found to work is by using this code snippet

```python
import sys
import types
sys.meta_path = [h for h in sys.meta_path if "PostImportHook" not in repr(h)]

for name, module in list(sys.modules.items()):
    if not isinstance(module, types.ModuleType):
        continue
    if getattr(module, "__file__", "") is not None and getattr(module, "__file__", "").startswith(
        "/databricks/spark/python/dlt"
    ):
        del sys.modules[name]

import dlt
```
